// This file is auto-generated by Payload during build.
// It maps custom component paths to their resolved modules.
// For now, this is an empty map until custom components are registered.
export const importMap = {}
