-- Migration 017: Seed Master Ranking with legacy data
-- Source: European OPC Master Ranking Google Sheet (scraped March 2026)
-- 601 players from 5 countries: Netherlands, Poland, Ireland, Germany, Belgium

-- Insert all players with their current total points
INSERT INTO master_players (name, name_normalized, nationality, total_points) VALUES
('Ed van Zelm', 'ed van zelm', 'Netherlands', 125),
('Ron Van gorselen', 'ron van gorselen', 'Netherlands', 119),
('Marco Los', 'marco los', 'Netherlands', 110),
('Leszek Rutkowski', 'leszek rutkowski', 'Netherlands', 101),
('Gerard Gulik', 'gerard gulik', 'Netherlands', 92),
('Andrii Chmelenko', 'andrii chmelenko', 'Netherlands', 78),
('Jelle Berk', 'jelle berk', 'Netherlands', 76),
('Rob Bronkhorst', 'rob bronkhorst', 'Netherlands', 73),
('Jesse Jonkman', 'jesse jonkman', 'Netherlands', 71),
('Raymond Wit', 'raymond wit', 'Netherlands', 69),
('Carl Schulz', 'carl schulz', 'Netherlands', 64),
('Daan Jonkers', 'daan jonkers', 'Netherlands', 64),
('Sander Swuste', 'sander swuste', 'Netherlands', 64),
('Joris Abelsma', 'joris abelsma', 'Netherlands', 62),
('Harald Hartono', 'harald hartono', 'Netherlands', 57),
('Marcel Plak', 'marcel plak', 'Netherlands', 56),
('Teunis Los', 'teunis los', 'Netherlands', 53),
('Theo Joustra', 'theo joustra', 'Netherlands', 52),
('Marc Bouter', 'marc bouter', 'Netherlands', 51),
('Ryan Wit', 'ryan wit', 'Netherlands', 51),
('Francisco Javier Tellez', 'francisco javier tellez', 'Netherlands', 49),
('Raoul Hussainali', 'raoul hussainali', 'Netherlands', 48),
('Paul Verheul', 'paul verheul', 'Netherlands', 47),
('Jeroen van den Berg', 'jeroen van den berg', 'Netherlands', 46),
('Kevin Michelsen', 'kevin michelsen', 'Netherlands', 46),
('Roderick Paling', 'roderick paling', 'Netherlands', 46),
('Aad de Jong', 'aad de jong', 'Netherlands', 45),
('Boris Scheer', 'boris scheer', 'Netherlands', 45),
('Mark Jan Baas', 'mark jan baas', 'Netherlands', 45),
('Richard van Maren', 'richard van maren', 'Netherlands', 45),
('Alice Van Der Horst', 'alice van der horst', 'Netherlands', 44),
('Raymond De Blanken', 'raymond de blanken', 'Netherlands', 44),
('Daniel Fakkert', 'daniel fakkert', 'Netherlands', 43),
('Anton van der Cruijsen', 'anton van der cruijsen', 'Netherlands', 42),
('Caspar De wolf', 'caspar de wolf', 'Netherlands', 42),
('Taco Tijsma', 'taco tijsma', 'Netherlands', 42),
('Ronald Hodes', 'ronald hodes', 'Netherlands', 40),
('Timo Hage', 'timo hage', 'Netherlands', 40),
('Mark van der Schuur', 'mark van der schuur', 'Netherlands', 39),
('Stef Rekers', 'stef rekers', 'Netherlands', 39),
('Boaz Zimbile', 'boaz zimbile', 'Netherlands', 38),
('Jeffrey Lamers', 'jeffrey lamers', 'Netherlands', 38),
('Bradley Van olst', 'bradley van olst', 'Netherlands', 36),
('Maikel Grant', 'maikel grant', 'Netherlands', 36),
('Patrick Van Duivenboden', 'patrick van duivenboden', 'Netherlands', 36),
('Rafello Pelhan', 'rafello pelhan', 'Netherlands', 36),
('Alberto Aramake', 'alberto aramake', 'Netherlands', 35),
('Richard Huizer', 'richard huizer', 'Netherlands', 35),
('Andrea Pessot', 'andrea pessot', 'Netherlands', 34),
('Sander Spruijt', 'sander spruijt', 'Netherlands', 34),
('Angelo De Wolf', 'angelo de wolf', 'Netherlands', 33),
('Badr Sila', 'badr sila', 'Netherlands', 33),
('Edwin Roovers', 'edwin roovers', 'Netherlands', 33),
('Niels Spruijt', 'niels spruijt', 'Netherlands', 33),
('Jakob Kruiswijk', 'jakob kruiswijk', 'Netherlands', 32),
('Jouke van Laar', 'jouke van laar', 'Netherlands', 32),
('Maarten Boshuis Kruijsbergen', 'maarten boshuis kruijsbergen', 'Netherlands', 32),
('Marcel Klabbers', 'marcel klabbers', 'Netherlands', 32),
('Nico Elzinga', 'nico elzinga', 'Netherlands', 32),
('Hassimiou Bah', 'hassimiou bah', 'Netherlands', 30),
('John-Lee Brewster', 'john-lee brewster', 'Netherlands', 30),
('mohamed Allel', 'mohamed allel', 'Netherlands', 30),
('Joop van der Meulen', 'joop van der meulen', 'Netherlands', 29),
('Leroy van Wijngaarden', 'leroy van wijngaarden', 'Netherlands', 29),
('johan de raad', 'johan de raad', 'Netherlands', 29),
('terry kroone', 'terry kroone', 'Netherlands', 29),
('Franklin Ribadeneira', 'franklin ribadeneira', 'Netherlands', 28),
('Angelo De wolf', 'angelo de wolf', 'Netherlands', 27),
('Dylan Verschoor', 'dylan verschoor', 'Netherlands', 27),
('Jorian Maliepaard', 'jorian maliepaard', 'Netherlands', 27),
('Karol Ruszkowski', 'karol ruszkowski', 'Netherlands', 27),
('Lennart van Koot', 'lennart van koot', 'Netherlands', 27),
('Marcel Fontijn', 'marcel fontijn', 'Netherlands', 27),
('Masoud Valiloo', 'masoud valiloo', 'Netherlands', 27),
('Mats Handgraaf', 'mats handgraaf', 'Netherlands', 27),
('Nathalie Mulder', 'nathalie mulder', 'Netherlands', 27),
('Ton Deerenberg', 'ton deerenberg', 'Netherlands', 27),
('Nico Zornig', 'nico zornig', 'Netherlands', 26),
('Peter Van Eeden', 'peter van eeden', 'Netherlands', 26),
('Robert Smit', 'robert smit', 'Netherlands', 26),
('Tim Bakelaar', 'tim bakelaar', 'Netherlands', 26),
('Yordy Kroone', 'yordy kroone', 'Netherlands', 26),
('Bartosz Ginalski', 'bartosz ginalski', 'Netherlands', 25),
('Johan de Jong', 'johan de jong', 'Netherlands', 25),
('Peter Gadellaa', 'peter gadellaa', 'Netherlands', 25),
('Peter Van den Nieuwenhof', 'peter van den nieuwenhof', 'Netherlands', 25),
('Renwar Hanina', 'renwar hanina', 'Netherlands', 25),
('Astrid Wijbenga', 'astrid wijbenga', 'Netherlands', 24),
('Barbara Zornig Stolk', 'barbara zornig stolk', 'Netherlands', 24),
('Ebi Verbeek', 'ebi verbeek', 'Netherlands', 24),
('Elmer Stouten', 'elmer stouten', 'Netherlands', 24),
('Jan Jurgens', 'jan jurgens', 'Netherlands', 24),
('Milan Damen', 'milan damen', 'Netherlands', 24),
('Mohamed Allel', 'mohamed allel', 'Netherlands', 24),
('Nick Breetvelt', 'nick breetvelt', 'Netherlands', 24),
('Nico Jansen', 'nico jansen', 'Netherlands', 24),
('dave blok', 'dave blok', 'Netherlands', 24),
('Maaiko Visser', 'maaiko visser', 'Netherlands', 23),
('Mark Horst', 'mark horst', 'Netherlands', 23),
('Stefan Visser', 'stefan visser', 'Netherlands', 23),
('Craig Gummer', 'craig gummer', 'Netherlands', 22),
('Frank Van ark', 'frank van ark', 'Netherlands', 22),
('Marco Nijhuis', 'marco nijhuis', 'Netherlands', 22),
('Niek Emmelot', 'niek emmelot', 'Netherlands', 22),
('Robin De Boer', 'robin de boer', 'Netherlands', 22),
('Andy Kizis', 'andy kizis', 'Netherlands', 21),
('Barbara Smith', 'barbara smith', 'Netherlands', 21),
('Carla Gul-Hopman', 'carla gul-hopman', 'Netherlands', 21),
('Dennis Sprong', 'dennis sprong', 'Netherlands', 21),
('Els Los', 'els los', 'Netherlands', 21),
('Elvir Keric', 'elvir keric', 'Netherlands', 21),
('Erik Top', 'erik top', 'Netherlands', 21),
('Ethel van der Schinkel', 'ethel van der schinkel', 'Netherlands', 21),
('Huig Van Duijvenvoorde', 'huig van duijvenvoorde', 'Netherlands', 21),
('Kiena Baijens', 'kiena baijens', 'Netherlands', 21),
('Martin de Wit', 'martin de wit', 'Netherlands', 21),
('Richard Oosterom', 'richard oosterom', 'Netherlands', 21),
('Sander Barendse', 'sander barendse', 'Netherlands', 21),
('Sander van Maanen', 'sander van maanen', 'Netherlands', 21),
('Stefan Scholten', 'stefan scholten', 'Netherlands', 21),
('Tygo Punt', 'tygo punt', 'Netherlands', 21),
('Cinthia Bolleboom', 'cinthia bolleboom', 'Netherlands', 20),
('Nylas van Deursen', 'nylas van deursen', 'Netherlands', 19),
('Eldor van Feggelen', 'eldor van feggelen', 'Netherlands', 18),
('Hans Mathon', 'hans mathon', 'Netherlands', 18),
('Jeroen Tesselaar', 'jeroen tesselaar', 'Netherlands', 18),
('Lev Persoon', 'lev persoon', 'Netherlands', 18),
('Patrick van Duivenboden', 'patrick van duivenboden', 'Netherlands', 18),
('Quentin Van der schinkel', 'quentin van der schinkel', 'Netherlands', 18),
('Ronald Roolker', 'ronald roolker', 'Netherlands', 18),
('Roy schinkel', 'roy schinkel', 'Netherlands', 18),
('Stanley Brussaard', 'stanley brussaard', 'Netherlands', 18),
('Filip Abgarowicz', 'filip abgarowicz', 'Poland', 18),
('Aisling Connor', 'aisling connor', 'Ireland', 18),
('Corjan Hokke', 'corjan hokke', 'Netherlands', 17),
('Peter De jager', 'peter de jager', 'Netherlands', 17),
('Pieter Knecht', 'pieter knecht', 'Netherlands', 17),
('Vincent Burger', 'vincent burger', 'Netherlands', 17),
('teun bakker', 'teun bakker', 'Netherlands', 17),
('Badr Bellahcen', 'badr bellahcen', 'Netherlands', 16),
('Gertjan Oosterman', 'gertjan oosterman', 'Netherlands', 16),
('Henk Horden', 'henk horden', 'Netherlands', 16),
('Alex Bor', 'alex bor', 'Netherlands', 15),
('Cor Tummers', 'cor tummers', 'Netherlands', 15),
('Frans Bronswijk', 'frans bronswijk', 'Netherlands', 15),
('Hooman Golkarian', 'hooman golkarian', 'Netherlands', 15),
('Jac Thiel', 'jac thiel', 'Netherlands', 15),
('Jakub Horodeński', 'jakub horodeński', 'Netherlands', 15),
('Jan Baijens', 'jan baijens', 'Netherlands', 15),
('Jan van der Vlugt', 'jan van der vlugt', 'Netherlands', 15),
('Jess van den Heuvel', 'jess van den heuvel', 'Netherlands', 15),
('Jona Eekhout', 'jona eekhout', 'Netherlands', 15),
('Joop Romkes', 'joop romkes', 'Netherlands', 15),
('Joris van Ewijk', 'joris van ewijk', 'Netherlands', 15),
('Jort van Delft', 'jort van delft', 'Netherlands', 15),
('Mark Van der horst', 'mark van der horst', 'Netherlands', 15),
('Matthias weerheim', 'matthias weerheim', 'Netherlands', 15),
('Niels Van de Koppel', 'niels van de koppel', 'Netherlands', 15),
('Peter Van Hengel', 'peter van hengel', 'Netherlands', 15),
('Stephan Bajo', 'stephan bajo', 'Netherlands', 15),
('Tim Rutten', 'tim rutten', 'Netherlands', 15),
('michel wever', 'michel wever', 'Netherlands', 15),
('Karol Brandt', 'karol brandt', 'Germany', 15),
('Dummy data 4 Dummy last 4', 'dummy data 4 dummy last 4', 'Belgium', 15),
('Agnieszka Abrahamczyk', 'agnieszka abrahamczyk', 'Poland', 15),
('Cillian Sullivan', 'cillian sullivan', 'Ireland', 15),
('Fabian Smit', 'fabian smit', 'Netherlands', 14),
('Hidde van Hal', 'hidde van hal', 'Netherlands', 14),
('Sebastiaan Albers', 'sebastiaan albers', 'Netherlands', 14),
('Alexander Aartsen', 'alexander aartsen', 'Netherlands', 13),
('Bram Damen', 'bram damen', 'Netherlands', 13),
('Camiel van Bedaf', 'camiel van bedaf', 'Netherlands', 13),
('Dylan Thielen', 'dylan thielen', 'Netherlands', 13),
('Lars van der Straten', 'lars van der straten', 'Netherlands', 13),
('Richard oosterom', 'richard oosterom', 'Netherlands', 13),
('Robin de Boer', 'robin de boer', 'Netherlands', 13),
('Andrzej Abrahamowicz', 'andrzej abrahamowicz', 'Poland', 13),
('Kieran Barry', 'kieran barry', 'Ireland', 13),
('Ahmet Gungor', 'ahmet gungor', 'Netherlands', 12),
('Arno van Hal', 'arno van hal', 'Netherlands', 12),
('Caspar De Wolf', 'caspar de wolf', 'Netherlands', 12),
('Edwin Veenendaal', 'edwin veenendaal', 'Netherlands', 12),
('Erik van Duijn', 'erik van duijn', 'Netherlands', 12),
('Heinz Bloch', 'heinz bloch', 'Netherlands', 12),
('Jan Nab', 'jan nab', 'Netherlands', 12),
('Johan de Raad', 'johan de raad', 'Netherlands', 12),
('John Valk', 'john valk', 'Netherlands', 12),
('Margot Kester', 'margot kester', 'Netherlands', 12),
('Mark Iske', 'mark iske', 'Netherlands', 12),
('Martin van Gijzen', 'martin van gijzen', 'Netherlands', 12),
('Milena Dobrijevic', 'milena dobrijevic', 'Netherlands', 12),
('Ricardo Outshoven', 'ricardo outshoven', 'Netherlands', 12),
('Rick Butter', 'rick butter', 'Netherlands', 12),
('Romeo Panchoe', 'romeo panchoe', 'Netherlands', 12),
('Rutger van Wely', 'rutger van wely', 'Netherlands', 12),
('Yedi De lanoe', 'yedi de lanoe', 'Netherlands', 12),
('vincent burger', 'vincent burger', 'Netherlands', 12),
('Alice Van der Horst', 'alice van der horst', 'Netherlands', 11),
('Dennis Krijgsman', 'dennis krijgsman', 'Netherlands', 11),
('Dorus Ros', 'dorus ros', 'Netherlands', 11),
('Jeroen Kreijne', 'jeroen kreijne', 'Netherlands', 11),
('Karim Touijri', 'karim touijri', 'Netherlands', 11),
('Lissy De Haan', 'lissy de haan', 'Netherlands', 11),
('Michel Baart', 'michel baart', 'Netherlands', 11),
('Michel Wever', 'michel wever', 'Netherlands', 11),
('Tom Laenen', 'tom laenen', 'Netherlands', 11),
('Antoni Abramczyk', 'antoni abramczyk', 'Poland', 11),
('Áine Boyle', 'áine boyle', 'Ireland', 11),
('Bas Molenaar', 'bas molenaar', 'Netherlands', 10),
('Khalid El Jerari', 'khalid el jerari', 'Netherlands', 10),
('Albert Blom', 'albert blom', 'Netherlands', 9),
('Amancio Ribadeneira', 'amancio ribadeneira', 'Netherlands', 9),
('Anouk Beumer', 'anouk beumer', 'Netherlands', 9),
('Asam Mian', 'asam mian', 'Netherlands', 9),
('Berry Alferink', 'berry alferink', 'Netherlands', 9),
('Camiel Carlier', 'camiel carlier', 'Netherlands', 9),
('Derek Hoogland', 'derek hoogland', 'Netherlands', 9),
('Dewi Van Dijk', 'dewi van dijk', 'Netherlands', 9),
('Djarno Wit', 'djarno wit', 'Netherlands', 9),
('Dominique Borgi', 'dominique borgi', 'Netherlands', 9),
('Dorus ros', 'dorus ros', 'Netherlands', 9),
('Ed van Empelen', 'ed van empelen', 'Netherlands', 9),
('Erwin Oudshoorn', 'erwin oudshoorn', 'Netherlands', 9),
('Jeroen Van den berg', 'jeroen van den berg', 'Netherlands', 9),
('Jop van Oudenaarden', 'jop van oudenaarden', 'Netherlands', 9),
('Jouke Van Laar', 'jouke van laar', 'Netherlands', 9),
('Lars van der Meer', 'lars van der meer', 'Netherlands', 9),
('Leroy Van Wijngaarden', 'leroy van wijngaarden', 'Netherlands', 9),
('Lucenda Codfried', 'lucenda codfried', 'Netherlands', 9),
('Marco Van Tuil', 'marco van tuil', 'Netherlands', 9),
('Mark Molier', 'mark molier', 'Netherlands', 9),
('Martijn Veen', 'martijn veen', 'Netherlands', 9),
('Martijn Zuidema', 'martijn zuidema', 'Netherlands', 9),
('Martti Reijne', 'martti reijne', 'Netherlands', 9),
('Massoud Valiloo', 'massoud valiloo', 'Netherlands', 9),
('Matthias Weerheim', 'matthias weerheim', 'Netherlands', 9),
('Max Verbeek', 'max verbeek', 'Netherlands', 9),
('Michel Legierse', 'michel legierse', 'Netherlands', 9),
('Moreno Blom', 'moreno blom', 'Netherlands', 9),
('Naomi Horsten', 'naomi horsten', 'Netherlands', 9),
('Oleksii Movchan', 'oleksii movchan', 'Netherlands', 9),
('Pascal Visser', 'pascal visser', 'Netherlands', 9),
('Peter Workum', 'peter workum', 'Netherlands', 9),
('Peter van den Nieuwenhof', 'peter van den nieuwenhof', 'Netherlands', 9),
('Rene Schelvis', 'rene schelvis', 'Netherlands', 9),
('Sanne van den Boom', 'sanne van den boom', 'Netherlands', 9),
('Sjoukje Leugs', 'sjoukje leugs', 'Netherlands', 9),
('Suzanne Van Der Horst', 'suzanne van der horst', 'Netherlands', 9),
('Timothy Janssen', 'timothy janssen', 'Netherlands', 9),
('Tommy van Brienen', 'tommy van brienen', 'Netherlands', 9),
('Yedi De Lanoe', 'yedi de lanoe', 'Netherlands', 9),
('angelo De wolf', 'angelo de wolf', 'Netherlands', 9),
('mohamed allel', 'mohamed allel', 'Netherlands', 9),
('Barbara Abramowicz', 'barbara abramowicz', 'Poland', 9),
('Aoife Brian', 'aoife brian', 'Ireland', 9),
('Debora Nowee', 'debora nowee', 'Netherlands', 8),
('Lesley van Houten', 'lesley van houten', 'Netherlands', 8),
('Martijn Punt', 'martijn punt', 'Netherlands', 8),
('Matz Boone', 'matz boone', 'Netherlands', 8),
('Quinten Hageman', 'quinten hageman', 'Netherlands', 8),
('R Markus', 'r markus', 'Netherlands', 8),
('Sebastiaan Diemel', 'sebastiaan diemel', 'Netherlands', 8),
('Aleksander Adamczak', 'aleksander adamczak', 'Poland', 8),
('Connor Kelly', 'connor kelly', 'Ireland', 8),
('Bert Duin', 'bert duin', 'Netherlands', 7),
('Margo Breddels', 'margo breddels', 'Netherlands', 7),
('Mark van de Schuur', 'mark van de schuur', 'Netherlands', 7),
('Ron Van Gorselen', 'ron van gorselen', 'Netherlands', 7),
('Tirza van Waardenburg', 'tirza van waardenburg', 'Netherlands', 7),
('pieter knecht', 'pieter knecht', 'Netherlands', 7),
('Wilhelm Kerstens', 'wilhelm kerstens', 'Germany', 7),
('Dummy data 5 Dummy last 5', 'dummy data 5 dummy last 5', 'Belgium', 7),
('Jakub Adamczuk', 'jakub adamczuk', 'Poland', 7),
('Rory Ryan', 'rory ryan', 'Ireland', 7),
('Alex Hertogs', 'alex hertogs', 'Netherlands', 6),
('Andrea Horsten', 'andrea horsten', 'Netherlands', 6),
('André Willigenburg', 'andré willigenburg', 'Netherlands', 6),
('Ashraf Dini', 'ashraf dini', 'Netherlands', 6),
('Bradley van Olst', 'bradley van olst', 'Netherlands', 6),
('Christian Boudewijn', 'christian boudewijn', 'Netherlands', 6),
('Danielle De wit', 'danielle de wit', 'Netherlands', 6),
('Danny Swart', 'danny swart', 'Netherlands', 6),
('Dave Blok', 'dave blok', 'Netherlands', 6),
('Erik Blom', 'erik blom', 'Netherlands', 6),
('Erwin Pleus', 'erwin pleus', 'Netherlands', 6),
('Eryk Lorke', 'eryk lorke', 'Netherlands', 6),
('Finn Kitzmann', 'finn kitzmann', 'Netherlands', 6),
('Frank van Ark', 'frank van ark', 'Netherlands', 6),
('Gerard van Oostenbrugge', 'gerard van oostenbrugge', 'Netherlands', 6),
('Ibrahim Aoulad Lfadil', 'ibrahim aoulad lfadil', 'Netherlands', 6),
('Jan Hoogenraad', 'jan hoogenraad', 'Netherlands', 6),
('Jeffrey van Reijen', 'jeffrey van reijen', 'Netherlands', 6),
('Jelte Van Duivenboden', 'jelte van duivenboden', 'Netherlands', 6),
('JoonSuk Janse', 'joonsuk janse', 'Netherlands', 6),
('Joost van der Blom', 'joost van der blom', 'Netherlands', 6),
('Jordy Vos', 'jordy vos', 'Netherlands', 6),
('Jos Koets', 'jos koets', 'Netherlands', 6),
('Jurriaan Kwakkel', 'jurriaan kwakkel', 'Netherlands', 6),
('Kamil Zglinicki', 'kamil zglinicki', 'Netherlands', 6),
('Kevin Haverkamp', 'kevin haverkamp', 'Netherlands', 6),
('Koos van der Spek', 'koos van der spek', 'Netherlands', 6),
('Kristel Bakker', 'kristel bakker', 'Netherlands', 6),
('Lesley Schutten', 'lesley schutten', 'Netherlands', 6),
('Lucas Meyer', 'lucas meyer', 'Netherlands', 6),
('Lucas Reppel', 'lucas reppel', 'Netherlands', 6),
('Lukasz Kuczera', 'lukasz kuczera', 'Netherlands', 6),
('Luuk Kleiweg', 'luuk kleiweg', 'Netherlands', 6),
('Mark Burrows', 'mark burrows', 'Netherlands', 6),
('Mark Veerman', 'mark veerman', 'Netherlands', 6),
('Mark van Elsacker', 'mark van elsacker', 'Netherlands', 6),
('Mark van der Horst', 'mark van der horst', 'Netherlands', 6),
('Martin Hummel', 'martin hummel', 'Netherlands', 6),
('Mathijs van Deuren', 'mathijs van deuren', 'Netherlands', 6),
('Mershad Golkarian', 'mershad golkarian', 'Netherlands', 6),
('Michael Colin', 'michael colin', 'Netherlands', 6),
('Michael Meijer', 'michael meijer', 'Netherlands', 6),
('Mika van Woudenberg', 'mika van woudenberg', 'Netherlands', 6),
('Niels Luyken', 'niels luyken', 'Netherlands', 6),
('Oskar Sobański', 'oskar sobański', 'Netherlands', 6),
('Philip Pool', 'philip pool', 'Netherlands', 6),
('Rene Joore', 'rene joore', 'Netherlands', 6),
('Ronnie Mol', 'ronnie mol', 'Netherlands', 6),
('Roy van Berkel', 'roy van berkel', 'Netherlands', 6),
('Stef rekers', 'stef rekers', 'Netherlands', 6),
('Stijn Doedens', 'stijn doedens', 'Netherlands', 6),
('Teun van Stein', 'teun van stein', 'Netherlands', 6),
('Tim Peereboom', 'tim peereboom', 'Netherlands', 6),
('Tommy Van Brienen', 'tommy van brienen', 'Netherlands', 6),
('Vincent de Heer', 'vincent de heer', 'Netherlands', 6),
('Wendy Wagemans', 'wendy wagemans', 'Netherlands', 6),
('Willem Vermeulen', 'willem vermeulen', 'Netherlands', 6),
('Wouter Dinnessen', 'wouter dinnessen', 'Netherlands', 6),
('Wouter Ravelli', 'wouter ravelli', 'Netherlands', 6),
('eldor van feggelen', 'eldor van feggelen', 'Netherlands', 6),
('pascal visser', 'pascal visser', 'Netherlands', 6),
('Johann Schmidt', 'johann schmidt', 'Germany', 6),
('Dummy data 1 Dummy last 1', 'dummy data 1 dummy last 1', 'Belgium', 6),
('Alicja Adamczyk', 'alicja adamczyk', 'Poland', 6),
('Aidan Byrne', 'aidan byrne', 'Ireland', 6),
('Antoine Vagevuur', 'antoine vagevuur', 'Netherlands', 5),
('Bram van Hout', 'bram van hout', 'Netherlands', 5),
('Carla Gul Hopman', 'carla gul hopman', 'Netherlands', 5),
('Leroy Van wijngaarden', 'leroy van wijngaarden', 'Netherlands', 5),
('Maarten Boshuis-Kruisbergen', 'maarten boshuis-kruisbergen', 'Netherlands', 5),
('Quentin van der Schinkel', 'quentin van der schinkel', 'Netherlands', 5),
('quinten oldekamp', 'quinten oldekamp', 'Netherlands', 5),
('Ewa Adamecki', 'ewa adamecki', 'Poland', 5),
('Aoibhinn Callaghan', 'aoibhinn callaghan', 'Ireland', 5),
('Adri Willemzorg', 'adri willemzorg', 'Netherlands', 3),
('Ahsley Ras', 'ahsley ras', 'Netherlands', 3),
('Aldair Almeida', 'aldair almeida', 'Netherlands', 3),
('Aldair Ameida', 'aldair ameida', 'Netherlands', 3),
('Alex Aartsen', 'alex aartsen', 'Netherlands', 3),
('Alex aartsen', 'alex aartsen', 'Netherlands', 3),
('Alex van Gemert', 'alex van gemert', 'Netherlands', 3),
('Alexander Pouwels', 'alexander pouwels', 'Netherlands', 3),
('Alicia van Velzen', 'alicia van velzen', 'Netherlands', 3),
('Andre Teunizen', 'andre teunizen', 'Netherlands', 3),
('Aradhya Aakarsh', 'aradhya aakarsh', 'Netherlands', 3),
('Arjan Elskamp', 'arjan elskamp', 'Netherlands', 3),
('Arjan Van Rhijn', 'arjan van rhijn', 'Netherlands', 3),
('Ashley Ras', 'ashley ras', 'Netherlands', 3),
('Badr Bellachen', 'badr bellachen', 'Netherlands', 3),
('Barbara Zornig stolk', 'barbara zornig stolk', 'Netherlands', 3),
('Bart Van dijk', 'bart van dijk', 'Netherlands', 3),
('Bas Verheul', 'bas verheul', 'Netherlands', 3),
('Ben van Vuuren', 'ben van vuuren', 'Netherlands', 3),
('Benjamin Stallenberg', 'benjamin stallenberg', 'Netherlands', 3),
('Bradey van Olst', 'bradey van olst', 'Netherlands', 3),
('Bradley Van Olst', 'bradley van olst', 'Netherlands', 3),
('Brain Fabies', 'brain fabies', 'Netherlands', 3),
('Bram de Later', 'bram de later', 'Netherlands', 3),
('Camiel Brandenburg', 'camiel brandenburg', 'Netherlands', 3),
('Carla Gul', 'carla gul', 'Netherlands', 3),
('Cem Par', 'cem par', 'Netherlands', 3),
('Chiel van der Zee', 'chiel van der zee', 'Netherlands', 3),
('Chris Wedel', 'chris wedel', 'Netherlands', 3),
('Cor Huisman', 'cor huisman', 'Netherlands', 3),
('Corne Aantjes', 'corne aantjes', 'Netherlands', 3),
('Daniel Schwegler', 'daniel schwegler', 'Netherlands', 3),
('Danny Heijstek', 'danny heijstek', 'Netherlands', 3),
('Danny Lanu', 'danny lanu', 'Netherlands', 3),
('Denis Guska', 'denis guska', 'Netherlands', 3),
('Denise Liu', 'denise liu', 'Netherlands', 3),
('Dennis Paijmans', 'dennis paijmans', 'Netherlands', 3),
('Dennis Spruijt', 'dennis spruijt', 'Netherlands', 3),
('Dennis van Riet', 'dennis van riet', 'Netherlands', 3),
('Derk Streefkerk', 'derk streefkerk', 'Netherlands', 3),
('Djordy Broersma', 'djordy broersma', 'Netherlands', 3),
('Duncan Oudshoorn', 'duncan oudshoorn', 'Netherlands', 3),
('Edwin Hendriks', 'edwin hendriks', 'Netherlands', 3),
('Edwin Veenndaal', 'edwin veenndaal', 'Netherlands', 3),
('Eldor Van feggelen', 'eldor van feggelen', 'Netherlands', 3),
('Eric van Dijk', 'eric van dijk', 'Netherlands', 3),
('Erik Oudshoorn', 'erik oudshoorn', 'Netherlands', 3),
('Erik Ruevekamp', 'erik ruevekamp', 'Netherlands', 3),
('Erik Seine', 'erik seine', 'Netherlands', 3),
('Erwin Hofman', 'erwin hofman', 'Netherlands', 3),
('Fatih Buyuksahin', 'fatih buyuksahin', 'Netherlands', 3),
('Felix Huikeshoven', 'felix huikeshoven', 'Netherlands', 3),
('Felix Verhoeven', 'felix verhoeven', 'Netherlands', 3),
('Francisco Tellez', 'francisco tellez', 'Netherlands', 3),
('Frank Van Ark', 'frank van ark', 'Netherlands', 3),
('Franklin Ribandeneira', 'franklin ribandeneira', 'Netherlands', 3),
('Ger Mulder', 'ger mulder', 'Netherlands', 3),
('Gertjan Oudshoorn', 'gertjan oudshoorn', 'Netherlands', 3),
('Gijs van der Ploeg', 'gijs van der ploeg', 'Netherlands', 3),
('Hans Mark Visser', 'hans mark visser', 'Netherlands', 3),
('Henk Gieszen', 'henk gieszen', 'Netherlands', 3),
('Henny de Leeuw', 'henny de leeuw', 'Netherlands', 3),
('Hooman Golkarion', 'hooman golkarion', 'Netherlands', 3),
('Ian Huijsman', 'ian huijsman', 'Netherlands', 3),
('Ignacio Martin', 'ignacio martin', 'Netherlands', 3),
('Ingmar Bego', 'ingmar bego', 'Netherlands', 3),
('Jakub HORODEŃSKI', 'jakub horodeński', 'Netherlands', 3),
('Jakub Horodenski', 'jakub horodenski', 'Netherlands', 3),
('Javier Tellez', 'javier tellez', 'Netherlands', 3),
('Jeffrey Luisman', 'jeffrey luisman', 'Netherlands', 3),
('Jens Johannesen', 'jens johannesen', 'Netherlands', 3),
('Jero Brokaar', 'jero brokaar', 'Netherlands', 3),
('Jeroen De Gier', 'jeroen de gier', 'Netherlands', 3),
('Jeroen Soer', 'jeroen soer', 'Netherlands', 3),
('Jesse de Kemp', 'jesse de kemp', 'Netherlands', 3),
('Jochem Hanssen', 'jochem hanssen', 'Netherlands', 3),
('Joey Fontijn', 'joey fontijn', 'Netherlands', 3),
('Joey Nanda', 'joey nanda', 'Netherlands', 3),
('Johan Jurgens', 'johan jurgens', 'Netherlands', 3),
('Johan Stoutjesdijk', 'johan stoutjesdijk', 'Netherlands', 3),
('Johan jurgens', 'johan jurgens', 'Netherlands', 3),
('John Krijnen', 'john krijnen', 'Netherlands', 3),
('John Schelvis', 'john schelvis', 'Netherlands', 3),
('John Schot', 'john schot', 'Netherlands', 3),
('John-lee Brewster', 'john-lee brewster', 'Netherlands', 3),
('Joon Suk Janse', 'joon suk janse', 'Netherlands', 3),
('Joost Van der blom', 'joost van der blom', 'Netherlands', 3),
('Joris van Eijsden', 'joris van eijsden', 'Netherlands', 3),
('Jorn De vente', 'jorn de vente', 'Netherlands', 3),
('Jort Van Delft', 'jort van delft', 'Netherlands', 3),
('Jozef van Oostrom', 'jozef van oostrom', 'Netherlands', 3),
('Kai ten Kate', 'kai ten kate', 'Netherlands', 3),
('Kerim M', 'kerim m', 'Netherlands', 3),
('Kevin Arens', 'kevin arens', 'Netherlands', 3),
('Koen Valster', 'koen valster', 'Netherlands', 3),
('Lennart Venema', 'lennart venema', 'Netherlands', 3),
('Leroy Schwegler', 'leroy schwegler', 'Netherlands', 3),
('Leroy van wijngaarden', 'leroy van wijngaarden', 'Netherlands', 3),
('Levi Gardien', 'levi gardien', 'Netherlands', 3),
('Levi Wijnschenk', 'levi wijnschenk', 'Netherlands', 3),
('Lissy de Haan', 'lissy de haan', 'Netherlands', 3),
('Loes Daal', 'loes daal', 'Netherlands', 3),
('Lorenzo Kapiteijn', 'lorenzo kapiteijn', 'Netherlands', 3),
('Los Marco', 'los marco', 'Netherlands', 3),
('MICHEL VAN TUNEN', 'michel van tunen', 'Netherlands', 3),
('Maarten Leeuwenkamp', 'maarten leeuwenkamp', 'Netherlands', 3),
('Maarten van Luipen', 'maarten van luipen', 'Netherlands', 3),
('Maickel Van loon', 'maickel van loon', 'Netherlands', 3),
('Manuel Schwegler', 'manuel schwegler', 'Netherlands', 3),
('Marcel Luske', 'marcel luske', 'Netherlands', 3),
('Marcel van Waardenburg', 'marcel van waardenburg', 'Netherlands', 3),
('Marcel van Wijk', 'marcel van wijk', 'Netherlands', 3),
('Marco Schoenmakers', 'marco schoenmakers', 'Netherlands', 3),
('Mark Lintel', 'mark lintel', 'Netherlands', 3),
('Mark Van Der Horst', 'mark van der horst', 'Netherlands', 3),
('Mark Van der Horst', 'mark van der horst', 'Netherlands', 3),
('Marloes Onrust', 'marloes onrust', 'Netherlands', 3),
('Martijn Arslan', 'martijn arslan', 'Netherlands', 3),
('Masoud Valoloo', 'masoud valoloo', 'Netherlands', 3),
('Massoud Valilloo', 'massoud valilloo', 'Netherlands', 3),
('Maurits Grashuis', 'maurits grashuis', 'Netherlands', 3),
('Max Ruzius', 'max ruzius', 'Netherlands', 3),
('Mehrshad Golkarian', 'mehrshad golkarian', 'Netherlands', 3),
('Melissa Schwegler', 'melissa schwegler', 'Netherlands', 3),
('Michael Resoort', 'michael resoort', 'Netherlands', 3),
('Michel Nowee', 'michel nowee', 'Netherlands', 3),
('Mick Frerix', 'mick frerix', 'Netherlands', 3),
('Mika Van woudenberg', 'mika van woudenberg', 'Netherlands', 3),
('Mike Bisschop-Baten', 'mike bisschop-baten', 'Netherlands', 3),
('Mike Wittekoek', 'mike wittekoek', 'Netherlands', 3),
('Miloushka Daal', 'miloushka daal', 'Netherlands', 3),
('Mohamed El Kanfoudi', 'mohamed el kanfoudi', 'Netherlands', 3),
('Naomi Babai', 'naomi babai', 'Netherlands', 3),
('Nick Breedveld', 'nick breedveld', 'Netherlands', 3),
('Nick Breetvelt', 'nick breetvelt', 'Netherlands', 3),
('Nick Rijsbaarman', 'nick rijsbaarman', 'Netherlands', 3),
('Nicky Miedema', 'nicky miedema', 'Netherlands', 3),
('Nico Zornig Stolk', 'nico zornig stolk', 'Netherlands', 3),
('Nicole Leeuwenkamp', 'nicole leeuwenkamp', 'Netherlands', 3),
('Niek emmelot', 'niek emmelot', 'Netherlands', 3),
('Nikky Verbeten', 'nikky verbeten', 'Netherlands', 3),
('Njord Hollander', 'njord hollander', 'Netherlands', 3),
('Noah Peereboom', 'noah peereboom', 'Netherlands', 3),
('Olivier van Dam', 'olivier van dam', 'Netherlands', 3),
('Otto Jan Leeverink', 'otto jan leeverink', 'Netherlands', 3),
('Pascal Ekelmans', 'pascal ekelmans', 'Netherlands', 3),
('Patrick Kapiteijn', 'patrick kapiteijn', 'Netherlands', 3),
('Patrick Van de Leur', 'patrick van de leur', 'Netherlands', 3),
('Patrick van de Leur', 'patrick van de leur', 'Netherlands', 3),
('Patrick van der schief', 'patrick van der schief', 'Netherlands', 3),
('Peter De Jager', 'peter de jager', 'Netherlands', 3),
('Peter Gadella', 'peter gadella', 'Netherlands', 3),
('Peter Gijsbers', 'peter gijsbers', 'Netherlands', 3),
('Peter de Jager', 'peter de jager', 'Netherlands', 3),
('Peter van Dijk', 'peter van dijk', 'Netherlands', 3),
('Peter-Paul Wentrup', 'peter-paul wentrup', 'Netherlands', 3),
('Pim van Gorkum', 'pim van gorkum', 'Netherlands', 3),
('Quinten van Doorn', 'quinten van doorn', 'Netherlands', 3),
('Rafael Deerenberg', 'rafael deerenberg', 'Netherlands', 3),
('Ralf Botermans', 'ralf botermans', 'Netherlands', 3),
('Ramon Kret', 'ramon kret', 'Netherlands', 3),
('Ramond Wit', 'ramond wit', 'Netherlands', 3),
('Raymond Colin', 'raymond colin', 'Netherlands', 3),
('Rene Postema', 'rene postema', 'Netherlands', 3),
('Rene Van Nijnatten', 'rene van nijnatten', 'Netherlands', 3),
('Rens Smit', 'rens smit', 'Netherlands', 3),
('René Schelvis', 'rené schelvis', 'Netherlands', 3),
('Ricardo Jacobs', 'ricardo jacobs', 'Netherlands', 3),
('Ricardo Kooper', 'ricardo kooper', 'Netherlands', 3),
('Rick Lokers', 'rick lokers', 'Netherlands', 3),
('Rinus Gul', 'rinus gul', 'Netherlands', 3),
('Ritchie Nieuwenhuijze', 'ritchie nieuwenhuijze', 'Netherlands', 3),
('Roel Laming', 'roel laming', 'Netherlands', 3),
('Ron Smits', 'ron smits', 'Netherlands', 3),
('Ronald Barendse', 'ronald barendse', 'Netherlands', 3),
('Rory Hart', 'rory hart', 'Netherlands', 3),
('Rosa Moesker', 'rosa moesker', 'Netherlands', 3),
('Roy Bezemer', 'roy bezemer', 'Netherlands', 3),
('Roy Schinkel', 'roy schinkel', 'Netherlands', 3),
('Sebastiaan Spanjaard', 'sebastiaan spanjaard', 'Netherlands', 3),
('Sebastiaan van Koert', 'sebastiaan van koert', 'Netherlands', 3),
('Siem Peijnenborg', 'siem peijnenborg', 'Netherlands', 3),
('Sisca Bronswijk', 'sisca bronswijk', 'Netherlands', 3),
('Sofie Verhoef', 'sofie verhoef', 'Netherlands', 3),
('Stefan Bajo', 'stefan bajo', 'Netherlands', 3),
('Stefan Van Schaik', 'stefan van schaik', 'Netherlands', 3),
('Suzanne van der Horst', 'suzanne van der horst', 'Netherlands', 3),
('Sven Willemsen', 'sven willemsen', 'Netherlands', 3),
('Tamara Guérain', 'tamara guérain', 'Netherlands', 3),
('Terence Hersbach', 'terence hersbach', 'Netherlands', 3),
('Terry Kroone', 'terry kroone', 'Netherlands', 3),
('Theo Stegena', 'theo stegena', 'Netherlands', 3),
('Thijs van den Brink', 'thijs van den brink', 'Netherlands', 3),
('Ticket ingeleverd Barendse', 'ticket ingeleverd barendse', 'Netherlands', 3),
('Tiemen Straver', 'tiemen straver', 'Netherlands', 3),
('Ties Reijne', 'ties reijne', 'Netherlands', 3),
('Tijmen de Beer', 'tijmen de beer', 'Netherlands', 3),
('Tim Damen', 'tim damen', 'Netherlands', 3),
('Tim Janssen', 'tim janssen', 'Netherlands', 3),
('Tristan Brinkhuis', 'tristan brinkhuis', 'Netherlands', 3),
('VINCENT BURGER', 'vincent burger', 'Netherlands', 3),
('Valerie van Velzen', 'valerie van velzen', 'Netherlands', 3),
('Vince Haaften', 'vince haaften', 'Netherlands', 3),
('Vince van Haaften', 'vince van haaften', 'Netherlands', 3),
('Vincent Brust', 'vincent brust', 'Netherlands', 3),
('Vincent Calis', 'vincent calis', 'Netherlands', 3),
('Walter Van der Donk', 'walter van der donk', 'Netherlands', 3),
('Wico Wanders', 'wico wanders', 'Netherlands', 3),
('Wilco Van Oosten', 'wilco van oosten', 'Netherlands', 3),
('Wilfred Van Duijne', 'wilfred van duijne', 'Netherlands', 3),
('Wilke de Jong', 'wilke de jong', 'Netherlands', 3),
('Willy Diemel-Vermeer', 'willy diemel-vermeer', 'Netherlands', 3),
('Xander Jansen', 'xander jansen', 'Netherlands', 3),
('Yanieck Koets', 'yanieck koets', 'Netherlands', 3),
('Yedi de lanoe', 'yedi de lanoe', 'Netherlands', 3),
('Youri Habing', 'youri habing', 'Netherlands', 3),
('dewi van dijk', 'dewi van dijk', 'Netherlands', 3),
('erik top', 'erik top', 'Netherlands', 3),
('ingmar bego', 'ingmar bego', 'Netherlands', 3),
('jan Bast', 'jan bast', 'Netherlands', 3),
('jan van der schief', 'jan van der schief', 'Netherlands', 3),
('johan jurgens', 'johan jurgens', 'Netherlands', 3),
('leroy Van Wijngaarden', 'leroy van wijngaarden', 'Netherlands', 3),
('maaiko visser', 'maaiko visser', 'Netherlands', 3),
('marcel van waardenburg', 'marcel van waardenburg', 'Netherlands', 3),
('marcel van wijk', 'marcel van wijk', 'Netherlands', 3),
('mark iske', 'mark iske', 'Netherlands', 3),
('rafael deerenberg', 'rafael deerenberg', 'Netherlands', 3),
('tommy van Brienen', 'tommy van brienen', 'Netherlands', 3),
('wesley Mijnals', 'wesley mijnals', 'Netherlands', 3),
('Kerstin Fecht', 'kerstin fecht', 'Germany', 3),
('Marianne Langenfeld', 'marianne langenfeld', 'Germany', 3),
('Dummy data 2 Dummy last 2', 'dummy data 2 dummy last 2', 'Belgium', 3),
('Dummy data 3 Dummy last 3', 'dummy data 3 dummy last 3', 'Belgium', 3),
('Agata Aizenberg', 'agata aizenberg', 'Poland', 3),
('Bazyli Aleksandrowicz', 'bazyli aleksandrowicz', 'Poland', 3),
('Franciszek Ambroziak', 'franciszek ambroziak', 'Poland', 3),
('Igor Adamiak', 'igor adamiak', 'Poland', 3),
('Jan Adamiec', 'jan adamiec', 'Poland', 3),
('Lena Adamkiewicz', 'lena adamkiewicz', 'Poland', 3),
('Szymon Adamowicz', 'szymon adamowicz', 'Poland', 3),
('Zofia Adamowski', 'zofia adamowski', 'Poland', 3),
('Zuzanna Anczok', 'zuzanna anczok', 'Poland', 3),
('Brian Campbell', 'brian campbell', 'Ireland', 3),
('Fiadh Connell', 'fiadh connell', 'Ireland', 3),
('Finley Fitzpatrick', 'finley fitzpatrick', 'Ireland', 3),
('Finn Gallagher', 'finn gallagher', 'Ireland', 3),
('Liam Hayes', 'liam hayes', 'Ireland', 3),
('Nolan Flannery', 'nolan flannery', 'Ireland', 3),
('Orla Murphy', 'orla murphy', 'Ireland', 3),
('Oscar Ahearn', 'oscar ahearn', 'Ireland', 3),
('Paddy Brady', 'paddy brady', 'Ireland', 3),
('Riley Clarke', 'riley clarke', 'Ireland', 3);

-- Create legacy points_entries for audit trail
INSERT INTO points_entries (player_id, points, event_label, uploaded_by)
SELECT id, total_points, 'Legacy import — March 2026', 'system'
FROM master_players;

-- Compute initial ranks
WITH ranked AS (
  SELECT id, DENSE_RANK() OVER (ORDER BY total_points DESC) as new_rank
  FROM master_players
)
UPDATE master_players mp SET rank = r.new_rank
FROM ranked r WHERE mp.id = r.id;
